name: Build and deploy on pull request test1234

on:
    pull_request:
        types:
            - closed
        branches:
            - main # Trigger the workflow on push to the deployment branch
    workflow_dispatch:
        inputs:
            version:
                description: "Commit hash (long) or tag to roll back to (leave empty for latest push). Check README for more info."
                required: false
                type: string

env:
    WORKING_DIRECTORY: ${{ vars.WORKING_DIRECTORY}}
    IIS_POOL_NAME: ${{secrets.IIS_POOL_NAME}}
    NAME_IIS_PROJECT_FOLDER: ${{vars.NAME_IIS_PROJECT_FOLDER}}
    PATH_IIS_BASE_FOLDER: ${{vars.PATH_IIS_BASE_FOLDER}}
jobs:
    build:
        if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
        defaults:
            run:
                working-directory: ${{vars.WORKING_DIRECTORY}} # Set the working directory for the test job
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.inputs.version || 'main' }}
                  fetch-depth: 0 # Fetch all history for all branches and tags

            - name: copy env
              run: |
                  copy-item -path "C:\iisServer\angular\web\environment.ts" -destination "src\\environments\\environment.ts"
              shell: powershell

            - name: Install dependencies
              run: |
                  pwd
                  npm install
              shell: powershell

            - name: Build Angular app
              run: |
                  echo "building app"
                  npm run build

    deploy:
        needs: build
        if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
        defaults:
            run:
                working-directory: ${{vars.WORKING_DIRECTORY}} # Set the working directory for the test job
        runs-on: self-hosted
        outputs:
            reusable_output: ${{ steps.process-step.outputs.step_output }}

        steps:
            - name: Stop IIS Site
              run: |
                  echo "stopping IIS server"
                  Stop-IISSite -name "${{env.IIS_POOL_NAME}}" -confirm:$false
              shell: powershell

            - name: Backup and deploy IIS Directory
              id: process-step
              uses: ./.github/actions
              with:
                  pathIISBaseFolder: "${{env.PATH_IIS_BASE_FOLDER}}"
                  nameIISProjectFolder: "${{env.NAME_IIS_PROJECT_FOLDER}}"
                  pathToBuildFolder: "${{env.WORKING_DIRECTORY}}\\dist\\script\\browser"

            - name: ensure succes
              if: steps.process-step.outputs.backup-and-deploy-output == 'true'
              run: |
                  if ((Get-IISSite -Name "${{env.IIS_POOL_NAME}}").state -ne "Started") {
                    Stop-WebAppPool "${{env.IIS_POOL_NAME}}"
                  }
                  exit 1
              shell: powershell


            - name: Start IIS Site
              run: |
                  echo "starting IIS server"
                  Start-IISSite -Name "${{env.IIS_POOL_NAME}}"
              shell: powershell
